apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-front.fullname" . }}-nginx-conf
  labels:
    {{- include "nginx-front.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       80;
      server_name  _;

      root   /usr/share/nginx/html;
      index  index.html index.htm;
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-Frame-Options "DENY" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Referrer-Policy "strict-origin-when-cross-origin" always;

      client_max_body_size 1m;

      location = /index.html {
          add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
          try_files $uri =404;
      }

      location ~* \.(?:js|css|ico|gif|jpe?g|png|svg|woff2?|ttf|eot)$ {
          add_header Cache-Control "public, max-age=31536000, immutable" always;
          try_files $uri =404;
      }

      # Serve SPA: always fall back to index.html
      location / {
        try_files $uri $uri/ /index.html;
      }

      {{- if .Values.backend.enabled }}
      # API proxy
      location {{ .Values.backend.path }} {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://{{ .Values.backend.serviceHost }}:{{ .Values.backend.servicePort }};
      }
      {{- end }}

      # Error pages
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
